import { atom } from 'recoil';
import { classInfoType } from '../types/classdetail';

//모든 수업 목록
export const classListState = atom<classInfoType[]>({
    key: 'classListState',
    default: [
        {
            className: '인간학1',
            classId: 1,
            credit: 2,
            category: '교양',
            subCategory: '기초교양',
        },
        {
            className: '그리스도교사상과문화',
            classId: 2,
            credit: 2,
            category: '교양',
            subCategory: '기초교양',
        },
        {
            className: '과학의 논쟁',
            classId: 3,
            credit: 3,
            category: '교양',
            subCategory: '중핵교양',
        },
        {
            className: '요가',
            classId: 4,
            credit: 3,
            category: '교양',
            subCategory: '자유교양',
        },
        {
            className: '사회와 문화',
            classId: 5,
            credit: 2,
            category: '교양',
            subCategory: '자유교양', 
        },       
        {
            className: '사회와 문화1',
            classId: 6,
            credit: 2,
            category: '교양',
            subCategory: '자유교양', 
        },
        {
            className: '사회와 문화2',
            classId: 7,
            credit: 2,
            category: '교양',
            subCategory: '자유교양', 
        },
        {
            className: '사회와 문화3',
            classId: 8,
            credit: 2,
            category: '교양',
            subCategory: '자유교양', 
        },
        {
            className: '사회와 문화4',
            classId: 9,
            credit: 2,
            category: '교양',
            subCategory: '자유교양', 
        },
        {
            className: '일반화학및실험1',
            classId: 10,
            credit: 3,
            category: '전공기초',
            major: '화학과',
            majorArea: '자연과학영역',
        },
        {
            className: '일반물리학및실험1',
            classId: 11,
            credit: 3,
            category: '전공기초',
            major: '물리학과',
            majorArea: '자연과학영역',
        },
        {
            className: '일반수학1 및 연습',
            classId: 12,
            credit: 3,
            category: '전공기초',
            major: '수학과',
            majorArea: '자연과학영역',
        },
        {
            className: '프로그래밍 및 실습1',
            classId: 13,
            credit: 3,
            category: '전공기초',
            major: '정보통신전자공학부',
            majorArea: '공학영역',
        },
        {
            className: '컴퓨터와프로그래밍1',
            classId: 14,
            credit: 3,
            category: '전공기초',
            major: '컴퓨터정보공학부',
            majorArea: '공학영역',
        },
        {
            className: '디지털콘텐츠창작입문',
            classId: 15,
            credit: 3,
            category: '전공기초',
            major: '미디어기술콘텐츠학과',
            majorArea: '공학영역',
        },
        {
            className: '전자회로1및실험',
            classId: 16,
            credit: 3,
            category: '전공',
            major: '정보통신전자공학부',
        },
        {
            className: '컴퓨터 구조',
            classId: 17,
            credit: 3,
            category: '전공',
            major: '컴퓨터정보공학부',
        },
        {
            className: '시스템 소프트웨어 실습',
            classId: 18,
            credit: 3,
            category: '전공',
            major: '컴퓨터정보공학부',
        }, 
        {
            className: '경영학개론',
            classId: 19,
            credit: 3,
            category: '전공',
            major: '경영학과',
        },
        {
            className: '미디어와 콘텐츠',
            classId: 20,
            credit: 3,
            category: '전공',
            major: '미디어기술콘텐츠학과',
        },
    ],
});
